//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFTHold
    {
        public int Remittance_Id { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Text { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string Security_Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> AccountNumber { get; set; }
    }
}
