//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetProspectCreditInfo
    {
        public System.Guid ProspectId { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Status { get; set; }
        public string Reason { get; set; }
        public string Plan { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> AccountNumber { get; set; }
    }
}
