//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class HamiltonLevel
    {
        public int ID { get; set; }
        public System.DateTime ImportDateTime { get; set; }
        public string ts_location { get; set; }
        public string tk_level { get; set; }
        public string rpt_date_ti { get; set; }
        public string tx_num_ti { get; set; }
        public string ts_tankserialnum { get; set; }
        public string base_id_ti { get; set; }
        public string address_bi { get; set; }
        public string city_bi { get; set; }
        public string state_bi { get; set; }
        public string ts_access { get; set; }
        public string tk_w_dau { get; set; }
        public string ts_capacity { get; set; }
        public string tat_ttanklow { get; set; }
        public string tat_ttankcrit { get; set; }
        public string ts_cat_1 { get; set; }
        public string ts_cat_2 { get; set; }
        public string ts_cat_3 { get; set; }
        public string ts_cat_4 { get; set; }
        public string ts_code { get; set; }
        public string base_temp { get; set; }
    }
}
