//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectDeniedAppPrinted
    {
        public System.Guid ProspectID { get; set; }
        public System.DateTime DatePrinted { get; set; }
    }
}
