//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsCalculatorData
    {
        public int SavingsCalculatorDataId { get; set; }
        public decimal FirstFillPrice { get; set; }
        public decimal AdvantageProgramPrice { get; set; }
        public decimal SalesTax { get; set; }
        public decimal CurrentPriceEntered { get; set; }
        public int AnnualUsageEntered { get; set; }
        public decimal FirstYearCalculated { get; set; }
        public decimal SecondYearCalculated { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
