//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Data.ORM.HFBDB1ST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public System.Guid ZipCodeId { get; set; }
        public string ZipCode1 { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Valid { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string NotifyAddress { get; set; }
    }
}
